<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FoodMenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Get category IDs
        $categories = DB::table('menu_categories')->pluck('id', 'name')->toArray();

        // Breakfast Items (10 items)
        $breakfastItems = [
            [
                'name' => 'Tapsilog',
                'description' => 'Filipino beef tapa with garlic fried rice and egg',
                'price' => 120.00,
                'ingredients' => json_encode(['Beef', 'Rice', 'Egg', 'Garlic', 'Soy Sauce']),
                'allergens' => json_encode(['Soy', 'Eggs']),
                'calories' => 550,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Longsilog',
                'description' => 'Sweet Filipino sausage with garlic rice and egg',
                'price' => 110.00,
                'ingredients' => json_encode(['Longanisa', 'Rice', 'Egg', 'Garlic']),
                'allergens' => json_encode(['Eggs']),
                'calories' => 600,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Bangsilog',
                'description' => 'Fried milkfish with garlic rice and egg',
                'price' => 130.00,
                'ingredients' => json_encode(['Bangus', 'Rice', 'Egg', 'Garlic', 'Vinegar']),
                'allergens' => json_encode(['Fish', 'Eggs']),
                'calories' => 520,
                'preparation_time' => 20,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Tocilog',
                'description' => 'Sweet cured pork with garlic rice and egg',
                'price' => 115.00,
                'ingredients' => json_encode(['Tocino', 'Rice', 'Egg', 'Garlic']),
                'allergens' => json_encode(['Eggs']),
                'calories' => 580,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Cornsilog',
                'description' => 'Corned beef with garlic rice and egg',
                'price' => 100.00,
                'ingredients' => json_encode(['Corned Beef', 'Rice', 'Egg', 'Garlic', 'Onions']),
                'allergens' => json_encode(['Eggs']),
                'calories' => 530,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Champorado',
                'description' => 'Chocolate rice porridge with dried fish',
                'price' => 80.00,
                'ingredients' => json_encode(['Glutinous Rice', 'Cocoa', 'Sugar', 'Milk', 'Tuyo']),
                'allergens' => json_encode(['Dairy', 'Fish']),
                'calories' => 350,
                'preparation_time' => 20,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Pancakes with Maple Syrup',
                'description' => 'Fluffy pancakes served with butter and maple syrup',
                'price' => 95.00,
                'ingredients' => json_encode(['Flour', 'Eggs', 'Milk', 'Butter', 'Maple Syrup']),
                'allergens' => json_encode(['Gluten', 'Eggs', 'Dairy']),
                'calories' => 420,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Eggs Benedict',
                'description' => 'Poached eggs on English muffin with hollandaise sauce',
                'price' => 150.00,
                'ingredients' => json_encode(['Eggs', 'English Muffin', 'Ham', 'Hollandaise Sauce']),
                'allergens' => json_encode(['Gluten', 'Eggs', 'Dairy']),
                'calories' => 480,
                'preparation_time' => 20,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Arroz Caldo',
                'description' => 'Filipino rice porridge with chicken',
                'price' => 90.00,
                'ingredients' => json_encode(['Rice', 'Chicken', 'Ginger', 'Garlic', 'Green Onions']),
                'allergens' => json_encode([]),
                'calories' => 380,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Pan de Sal with Kesong Puti',
                'description' => 'Filipino bread rolls with white cheese',
                'price' => 60.00,
                'ingredients' => json_encode(['Bread', 'Kesong Puti', 'Butter']),
                'allergens' => json_encode(['Gluten', 'Dairy']),
                'calories' => 280,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        // Lunch Items (10 items)
        $lunchItems = [
            [
                'name' => 'Adobo',
                'description' => 'Classic Filipino chicken and pork adobo',
                'price' => 140.00,
                'ingredients' => json_encode(['Chicken', 'Pork', 'Soy Sauce', 'Vinegar', 'Garlic', 'Bay Leaves']),
                'allergens' => json_encode(['Soy']),
                'calories' => 520,
                'preparation_time' => 30,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Sinigang na Baboy',
                'description' => 'Sour pork soup with vegetables',
                'price' => 150.00,
                'ingredients' => json_encode(['Pork', 'Tamarind', 'Tomatoes', 'Kangkong', 'Radish', 'Eggplant']),
                'allergens' => json_encode([]),
                'calories' => 380,
                'preparation_time' => 35,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Kare-Kare',
                'description' => 'Oxtail and vegetables in peanut sauce',
                'price' => 180.00,
                'ingredients' => json_encode(['Oxtail', 'Peanut Butter', 'Eggplant', 'String Beans', 'Bagoong']),
                'allergens' => json_encode(['Peanuts']),
                'calories' => 620,
                'preparation_time' => 40,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Lechon Kawali',
                'description' => 'Crispy fried pork belly',
                'price' => 160.00,
                'ingredients' => json_encode(['Pork Belly', 'Garlic', 'Bay Leaves', 'Peppercorns']),
                'allergens' => json_encode([]),
                'calories' => 680,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Crispy Pata',
                'description' => 'Deep-fried pork knuckle',
                'price' => 350.00,
                'ingredients' => json_encode(['Pork Leg', 'Garlic', 'Bay Leaves', 'Peppercorns']),
                'allergens' => json_encode([]),
                'calories' => 850,
                'preparation_time' => 45,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Sisig',
                'description' => 'Sizzling chopped pork with onions and chili',
                'price' => 145.00,
                'ingredients' => json_encode(['Pork', 'Chicken Liver', 'Onions', 'Calamansi', 'Chili']),
                'allergens' => json_encode([]),
                'calories' => 540,
                'preparation_time' => 20,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Bulalo',
                'description' => 'Beef shank soup with bone marrow',
                'price' => 200.00,
                'ingredients' => json_encode(['Beef Shank', 'Bone Marrow', 'Corn', 'Cabbage', 'Potatoes']),
                'allergens' => json_encode([]),
                'calories' => 480,
                'preparation_time' => 50,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Pinakbet',
                'description' => 'Mixed vegetables with shrimp paste',
                'price' => 120.00,
                'ingredients' => json_encode(['Squash', 'Eggplant', 'Okra', 'String Beans', 'Bagoong', 'Pork']),
                'allergens' => json_encode([]),
                'calories' => 320,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Bicol Express',
                'description' => 'Spicy pork in coconut milk',
                'price' => 155.00,
                'ingredients' => json_encode(['Pork', 'Coconut Milk', 'Shrimp Paste', 'Chili Peppers', 'Garlic']),
                'allergens' => json_encode([]),
                'calories' => 590,
                'preparation_time' => 30,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Caldereta',
                'description' => 'Beef stew in tomato sauce',
                'price' => 165.00,
                'ingredients' => json_encode(['Beef', 'Tomato Sauce', 'Liver Spread', 'Potatoes', 'Carrots', 'Bell Peppers']),
                'allergens' => json_encode([]),
                'calories' => 550,
                'preparation_time' => 35,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        // Dinner Items (10 items)
        $dinnerItems = [
            [
                'name' => 'Grilled Bangus',
                'description' => 'Grilled milkfish stuffed with tomatoes and onions',
                'price' => 180.00,
                'ingredients' => json_encode(['Bangus', 'Tomatoes', 'Onions', 'Calamansi']),
                'allergens' => json_encode(['Fish']),
                'calories' => 420,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Beef Steak Tagalog',
                'description' => 'Filipino-style beef steak in soy and calamansi',
                'price' => 195.00,
                'ingredients' => json_encode(['Beef', 'Soy Sauce', 'Calamansi', 'Onions', 'Garlic']),
                'allergens' => json_encode(['Soy']),
                'calories' => 580,
                'preparation_time' => 30,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Fried Chicken',
                'description' => 'Crispy fried chicken served with rice',
                'price' => 140.00,
                'ingredients' => json_encode(['Chicken', 'Flour', 'Spices']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 620,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Sweet and Sour Fish',
                'description' => 'Fried fish fillet in sweet and sour sauce',
                'price' => 170.00,
                'ingredients' => json_encode(['Fish', 'Pineapple', 'Bell Peppers', 'Vinegar', 'Sugar']),
                'allergens' => json_encode(['Fish', 'Gluten']),
                'calories' => 480,
                'preparation_time' => 20,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Chicken Inasal',
                'description' => 'Grilled chicken marinated in lemongrass',
                'price' => 155.00,
                'ingredients' => json_encode(['Chicken', 'Lemongrass', 'Calamansi', 'Garlic', 'Ginger']),
                'allergens' => json_encode([]),
                'calories' => 450,
                'preparation_time' => 30,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Pork BBQ',
                'description' => 'Grilled marinated pork skewers',
                'price' => 130.00,
                'ingredients' => json_encode(['Pork', 'Soy Sauce', 'Calamansi', 'Brown Sugar', 'Garlic']),
                'allergens' => json_encode(['Soy']),
                'calories' => 520,
                'preparation_time' => 25,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Seafood Platter',
                'description' => 'Mixed grilled seafood with garlic butter',
                'price' => 380.00,
                'ingredients' => json_encode(['Shrimp', 'Squid', 'Fish', 'Mussels', 'Butter', 'Garlic']),
                'allergens' => json_encode(['Shellfish', 'Fish', 'Dairy']),
                'calories' => 650,
                'preparation_time' => 35,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Grilled Liempo',
                'description' => 'Grilled pork belly with atchara',
                'price' => 175.00,
                'ingredients' => json_encode(['Pork Belly', 'Soy Sauce', 'Calamansi', 'Garlic']),
                'allergens' => json_encode(['Soy']),
                'calories' => 720,
                'preparation_time' => 30,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Chicken Curry',
                'description' => 'Filipino-style chicken curry with vegetables',
                'price' => 145.00,
                'ingredients' => json_encode(['Chicken', 'Curry Powder', 'Coconut Milk', 'Potatoes', 'Carrots']),
                'allergens' => json_encode([]),
                'calories' => 510,
                'preparation_time' => 30,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Tinolang Manok',
                'description' => 'Chicken soup with ginger and papaya',
                'price' => 135.00,
                'ingredients' => json_encode(['Chicken', 'Ginger', 'Green Papaya', 'Malunggay', 'Fish Sauce']),
                'allergens' => json_encode([]),
                'calories' => 350,
                'preparation_time' => 35,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        // Dessert Items (10 items)
        $dessertItems = [
            [
                'name' => 'Halo-Halo',
                'description' => 'Mixed shaved ice dessert with fruits and beans',
                'price' => 95.00,
                'ingredients' => json_encode(['Shaved Ice', 'Ube', 'Leche Flan', 'Beans', 'Fruits', 'Milk', 'Ice Cream']),
                'allergens' => json_encode(['Dairy', 'Eggs']),
                'calories' => 380,
                'preparation_time' => 10,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Leche Flan',
                'description' => 'Filipino caramel custard',
                'price' => 70.00,
                'ingredients' => json_encode(['Eggs', 'Condensed Milk', 'Evaporated Milk', 'Sugar']),
                'allergens' => json_encode(['Eggs', 'Dairy']),
                'calories' => 320,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Buko Pandan',
                'description' => 'Coconut and pandan jelly salad',
                'price' => 75.00,
                'ingredients' => json_encode(['Young Coconut', 'Pandan Jelly', 'Cream', 'Condensed Milk']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 290,
                'preparation_time' => 8,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Ube Halaya',
                'description' => 'Purple yam jam dessert',
                'price' => 80.00,
                'ingredients' => json_encode(['Ube', 'Condensed Milk', 'Butter', 'Coconut Milk']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 310,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Maja Blanca',
                'description' => 'Coconut pudding with corn',
                'price' => 65.00,
                'ingredients' => json_encode(['Coconut Milk', 'Corn', 'Cornstarch', 'Sugar']),
                'allergens' => json_encode([]),
                'calories' => 260,
                'preparation_time' => 10,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Turon',
                'description' => 'Fried banana spring rolls',
                'price' => 55.00,
                'ingredients' => json_encode(['Banana', 'Brown Sugar', 'Spring Roll Wrapper', 'Jackfruit']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 280,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Bibingka',
                'description' => 'Filipino rice cake with salted egg',
                'price' => 60.00,
                'ingredients' => json_encode(['Rice Flour', 'Coconut Milk', 'Eggs', 'Cheese', 'Salted Egg']),
                'allergens' => json_encode(['Eggs', 'Dairy']),
                'calories' => 270,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Puto Bumbong',
                'description' => 'Purple sticky rice cake',
                'price' => 50.00,
                'ingredients' => json_encode(['Purple Rice', 'Coconut', 'Sugar', 'Butter']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 240,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Suman',
                'description' => 'Sticky rice wrapped in banana leaves',
                'price' => 45.00,
                'ingredients' => json_encode(['Glutinous Rice', 'Coconut Milk', 'Sugar']),
                'allergens' => json_encode([]),
                'calories' => 220,
                'preparation_time' => 10,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Banana Split',
                'description' => 'Classic ice cream dessert with banana',
                'price' => 110.00,
                'ingredients' => json_encode(['Banana', 'Ice Cream', 'Chocolate Syrup', 'Whipped Cream', 'Cherry']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 520,
                'preparation_time' => 8,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        // Snacks Items (10 items)
        $snacksItems = [
            [
                'name' => 'Lumpia Shanghai',
                'description' => 'Filipino spring rolls with ground pork',
                'price' => 85.00,
                'ingredients' => json_encode(['Pork', 'Vegetables', 'Spring Roll Wrapper', 'Garlic']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 340,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'Tokwa\'t Baboy',
                'description' => 'Fried tofu and pork with soy-vinegar sauce',
                'price' => 90.00,
                'ingredients' => json_encode(['Tofu', 'Pork', 'Soy Sauce', 'Vinegar', 'Onions']),
                'allergens' => json_encode(['Soy']),
                'calories' => 310,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Kwek-Kwek',
                'description' => 'Deep-fried battered quail eggs',
                'price' => 65.00,
                'ingredients' => json_encode(['Quail Eggs', 'Flour', 'Food Coloring']),
                'allergens' => json_encode(['Eggs', 'Gluten']),
                'calories' => 280,
                'preparation_time' => 10,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Fish Balls',
                'description' => 'Fried fish balls with sweet and spicy sauce',
                'price' => 55.00,
                'ingredients' => json_encode(['Fish Paste', 'Flour', 'Spices']),
                'allergens' => json_encode(['Fish', 'Gluten']),
                'calories' => 250,
                'preparation_time' => 10,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Chicken Wings',
                'description' => 'Crispy fried chicken wings',
                'price' => 95.00,
                'ingredients' => json_encode(['Chicken Wings', 'Flour', 'Spices', 'Garlic']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 420,
                'preparation_time' => 18,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Calamares',
                'description' => 'Fried squid rings with mayo dip',
                'price' => 105.00,
                'ingredients' => json_encode(['Squid', 'Flour', 'Breadcrumbs', 'Lemon']),
                'allergens' => json_encode(['Shellfish', 'Gluten', 'Eggs']),
                'calories' => 360,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Dynamite',
                'description' => 'Stuffed chili peppers wrapped in spring roll',
                'price' => 75.00,
                'ingredients' => json_encode(['Chili Peppers', 'Cheese', 'Spring Roll Wrapper']),
                'allergens' => json_encode(['Dairy', 'Gluten']),
                'calories' => 290,
                'preparation_time' => 12,
                'is_spicy' => true,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Cheese Sticks',
                'description' => 'Fried cheese wrapped in spring roll',
                'price' => 70.00,
                'ingredients' => json_encode(['Cheese', 'Spring Roll Wrapper']),
                'allergens' => json_encode(['Dairy', 'Gluten']),
                'calories' => 310,
                'preparation_time' => 10,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'French Fries',
                'description' => 'Crispy golden french fries',
                'price' => 60.00,
                'ingredients' => json_encode(['Potatoes', 'Salt']),
                'allergens' => json_encode([]),
                'calories' => 320,
                'preparation_time' => 12,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Nachos Supreme',
                'description' => 'Tortilla chips with beef, cheese, and toppings',
                'price' => 120.00,
                'ingredients' => json_encode(['Tortilla Chips', 'Ground Beef', 'Cheese', 'Salsa', 'Sour Cream']),
                'allergens' => json_encode(['Dairy', 'Gluten']),
                'calories' => 580,
                'preparation_time' => 15,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
        ];

        // Drinks Items (10 items)
        $drinksItems = [
            [
                'name' => 'Calamansi Juice',
                'description' => 'Fresh Filipino lime juice',
                'price' => 45.00,
                'ingredients' => json_encode(['Calamansi', 'Water', 'Sugar']),
                'allergens' => json_encode([]),
                'calories' => 80,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => true,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'Mango Shake',
                'description' => 'Fresh mango blended with milk',
                'price' => 75.00,
                'ingredients' => json_encode(['Mango', 'Milk', 'Sugar', 'Ice']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 220,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
            ],
            [
                'name' => 'Buko Juice',
                'description' => 'Fresh young coconut water',
                'price' => 50.00,
                'ingredients' => json_encode(['Young Coconut']),
                'allergens' => json_encode([]),
                'calories' => 45,
                'preparation_time' => 3,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'Sago\'t Gulaman',
                'description' => 'Tapioca pearls and gelatin drink',
                'price' => 40.00,
                'ingredients' => json_encode(['Tapioca Pearls', 'Gelatin', 'Brown Sugar', 'Water']),
                'allergens' => json_encode([]),
                'calories' => 150,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'Iced Coffee',
                'description' => 'Cold brewed coffee with milk',
                'price' => 65.00,
                'ingredients' => json_encode(['Coffee', 'Milk', 'Sugar', 'Ice']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 120,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
            ],
            [
                'name' => 'Four Seasons',
                'description' => 'Mixed fruit juice blend',
                'price' => 70.00,
                'ingredients' => json_encode(['Orange', 'Pineapple', 'Mango', 'Guava', 'Sugar']),
                'allergens' => json_encode([]),
                'calories' => 180,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'San Miguel Beer',
                'description' => 'Philippine lager beer',
                'price' => 80.00,
                'ingredients' => json_encode(['Barley', 'Hops', 'Water']),
                'allergens' => json_encode(['Gluten']),
                'calories' => 140,
                'preparation_time' => 2,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'Iced Tea',
                'description' => 'Refreshing lemon iced tea',
                'price' => 50.00,
                'ingredients' => json_encode(['Tea', 'Lemon', 'Sugar', 'Ice']),
                'allergens' => json_encode([]),
                'calories' => 90,
                'preparation_time' => 4,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'Bottomless Soda',
                'description' => 'Unlimited soft drinks',
                'price' => 55.00,
                'ingredients' => json_encode(['Carbonated Water', 'Syrup']),
                'allergens' => json_encode([]),
                'calories' => 140,
                'preparation_time' => 2,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
                'is_vegan' => true,
            ],
            [
                'name' => 'Hot Chocolate',
                'description' => 'Rich hot chocolate drink',
                'price' => 60.00,
                'ingredients' => json_encode(['Cocoa', 'Milk', 'Sugar']),
                'allergens' => json_encode(['Dairy']),
                'calories' => 200,
                'preparation_time' => 5,
                'is_spicy' => false,
                'is_available' => true,
                'is_featured' => false,
                'is_vegetarian' => true,
            ],
        ];

        // Insert items
        foreach ($breakfastItems as $item) {
            if (isset($categories['Breakfast'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Breakfast'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        foreach ($lunchItems as $item) {
            if (isset($categories['Lunch'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Lunch'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        foreach ($dinnerItems as $item) {
            if (isset($categories['Dinner'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Dinner'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        foreach ($dessertItems as $item) {
            if (isset($categories['Dessert'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Dessert'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        foreach ($snacksItems as $item) {
            if (isset($categories['Snacks'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Snacks'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        foreach ($drinksItems as $item) {
            if (isset($categories['Drinks'])) {
                DB::table('menu_items')->insert(array_merge($item, [
                    'menu_category_id' => $categories['Drinks'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ]));
            }
        }

        $this->command->info('Food menu seeded successfully with 60 items!');
    }
}
